-- Diagrams saved to the server

CREATE TABLE diagrams (
  -- Generated by the client (it needs the id before the first save)
  id         UUID PRIMARY KEY,
  owner_id   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name       TEXT NOT NULL DEFAULT '',
  database   TEXT NOT NULL DEFAULT 'generic',
  -- tables, references, notes, areas, views, types, enums, pan, zoom...
  content    JSONB NOT NULL,
  size_bytes INTEGER NOT NULL DEFAULT 0,
  -- Bumped on every save; a save based on an older version is a conflict
  version    INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Set when moved to the trash
  deleted_at TIMESTAMPTZ
);

CREATE INDEX diagrams_owner_active_idx ON diagrams (owner_id, updated_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX diagrams_owner_trash_idx ON diagrams (owner_id, deleted_at DESC) WHERE deleted_at IS NOT NULL;
